WEAPON_HASH = {
    'VEHICLE_ROCKET': 0xBEFDC581,
}


WEAPON_LIST = [
    "Melee 冷兵器",
    ("GOLFCLUB", "高尔夫球杆", 0x440E4788),
    ("HAMMER", "铁锤", 0x4E875F73),
    ("NIGHTSTICK", "警棍", 0x678B81B1),
    ("CROWBAR", "铁撬", 0x84BD7BFD),
    ("DAGGER", "古董骑兵匕首", 0x92A27487),
    ("BAT", "球棒", 0x958A4A8F),
    ("KNIFE", "小刀", 0x99B507EA),
    ("HANDCUFFS", "手铐", 0xD04C944D),
    ("GARBAGEBAG", "垃圾袋", 0xE232C28C),
    ("BOTTLE", "瓶子", 0xF9E6AA4B),

    "Pistol 手枪",
    ("PISTOL", "手枪", 0x1B06D571),
    ("COMBATPISTOL", "战斗手枪", 0x5EF9FEC4),
    ("PISTOL50", "50口径手枪", 0x99AEEB3B),
    ("SNSPISTOL", "劣质手枪", 0xBFD21232),
    ("HEAVYPISTOL", "重型手枪", 0xD205520E),
    ("VINTAGEPISTOL", "复古手枪", 0x083839C4),
    ("MARKSMANPISTOL", "射手手枪", 0xDC4DB296),
    ("APPISTOL", "穿甲手枪", 0x22D8FE39),
    ("STUNGUN", "电击枪", 0x3656C8C1),
    ("FLAREGUN", "闪光弹枪", 0x47757124),

    "ShotGun 霰弹枪",
    ("PUMPSHOTGUN", "泵动式霰弹枪", 0x1D073A89),
    ("SAWNOFFSHOTGUN", "削短型霰弹枪", 0x7846A318),
    ("BULLPUPSHOTGUN", "犊牛式霰弹枪", 0x9D61E50F),
    ("ASSAULTSHOTGUN", "突击霰弹枪", 0xE284C527),
    ("MUSKET", "老式火枪", 0xA89CB99E),
    ("HEAVYSHOTGUN", "重型霰弹枪", 0x3AABBBAA),
    
    "SMG 微冲 / MG 冲锋枪",
    ("MICROSMG", "小型冲锋枪", 0x13532244),
    ("SMG", "冲锋枪", 0x2BE6766B),
    ("ASSAULTSMG", "突击冲锋枪", 0xEFE7E2DF),
    ("COMBATPDW", "战斗自卫冲锋枪", 0xA3D4D34),
    ("MG", "机关枪", 0x9D07F764),
    ("COMBATMG", "战斗机关枪", 0x7FD62962),
    ("GUSENBERG", "古森柏冲锋枪", 0x61012683),

    "AssaultRifle 步枪",
    ("ASSAULTRIFLE", "突击步枪", 0xBFEFFF6D),
    ("CARBINERIFLE", "卡宾步枪", 0x83BF0278),
    ("ADVANCEDRIFLE", "高阶步枪", 0xAF113F99),
    ("SPECIALCARBINE", "特制卡宾步枪", 0xC0A3098D),
    ("BULLPUPRIFLE", "犊牛式步枪", 0x7F229F94),

    "Sniper 狙击枪",
    ("SNIPERRIFLE", "狙击枪", 0x05FC3C11),
    ("HEAVYSNIPER", "重型狙击枪", 0x0C472FE2),
    ("MARKSMANRIFLE", "射手步枪", 0xC734385A),

    "Heavy 重武器",
    ("GRENADELAUNCHER", "榴弹发射器", 0xA284510B),
    ("RPG", "火箭砲", 0xB1CA77B1),
    ("PASSENGER_ROCKET", "不可使用火箭筒", 0x166218FF),
    ("STINGER", "火箭砲", 0x687652CE),
    ("MINIGUN", "火神机枪", 0x42BF8A85),
    ("FIREWORK", "烟火发射器", 0x7F7497E5),
    ("RAILGUN", "镭射枪", 0x6D544C99),
    ("HOMINGLAUNCHER", "追踪弹发射器", 0x63AB0442),
    ("GRENADELAUNCHER_SMOKE", "烟雾弹发射器", 0x4DD2DC56),
    ("AIRSTRIKE_ROCKET", "空袭", 0x13579279),
    ("VEHICLE_ROCKET", "车载火箭炮", 0xBEFDC581),

    "Thrown 投掷物",
    ("GRENADE", "手榴弹", 0x93E220BD),
    ("STICKYBOMB", "黏弹", 0x2C3731D9),
    ("PROXMINE", "感应式地雷", 0xAB564B93),
    ("SMOKEGRENADE", "催泪瓦斯", 0xFDBC8A50),
    ("BZGAS", "毒气弹", 0xA0973D5E),
    ("MOLOTOV", "汽油弹", 0x24B17070),
    ("FIREEXTINGUISHER", "灭火器", 0x060EC506),
    ("PETROLCAN", "汽油桶", 0x34A67B97),
    ("BALL", "球", 0x23C9F95C),
    ("SNOWBALL", "雪球", 0x787F0BB),
    ("FLARE", "信号弹", 0x497FACC3),

    "其他",
    ("KNUCKLE", "指节套环", 0xD8DF3C3C),
    ("DIGISCANNER", "串口扫描仪", 0xFDBADCED),
    ("BRIEFCASE_02", "公文包02", 0x01B79F17),
    ("BRIEFCASE", "公文包", 0x88C78EB7),
]


VEHICLE_LIST = (
    ("ADDER", 0xB779A091),
    ("AIRBUS", 0x4C80EB0E),
    ("AIRTUG", 0x5D0AAC8F),
    ("AKUMA", 0x63ABADE7),
    ("ALPHA", 0x2DB8D1AA),
    ("AMBULANCE", 0x45D56ADA),
    ("ANNIHILATOR", 0x31F0B376),
    ("ARMYTANKER", 0xB8081009),
    ("ARMYTRAILER", 0xA7FF33F5),
    ("ARMYTRAILER2", 0x9E6B14D6),
    ("ASEA", 0x94204D89),
    ("ASEA2", 0x9441D8D5),
    ("ASTEROPE", 0x8E9254FB),
    ("BAGGER", 0x806B9CC3),
    ("BALETRAILER", 0xE82AE656),
    ("BALLER", 0xCFCA3668),
    ("BALLER2", 0x08852855),
    ("BANSHEE", 0xC1E908D2),
    ("BARRACKS", 0xCEEA3F4B),
    ("BARRACKS2", 0x4008EABB),
    ("BARRACKS3", 0x2592B5CF),
    ("BATI", 0xF9300CC5),
    ("BATI2", 0xCADD5D2D),
    ("BENSON", 0x7A61B330),
    ("BESRA", 0x6CBD1D6D),
    ("BFINJECTION", 0x432AA566),
    ("BIFF", 0x32B91AE8),
    ("BIFTA", 0xEB298297),
    ("BISON", 0xFEFD644F),
    ("BISON2", 0x7B8297C5),
    ("BISON3", 0x67B3F020),
    ("BJXL", 0x32B29A4B),
    ("BLADE", 0xB820ED5E),
    ("BLAZER", 0x8125BCF9),
    ("BLAZER2", 0xFD231729),
    ("BLAZER3", 0xB44F0582),
    ("BLIMP", 0xF7004C86),
    ("BLIMP2", 0xDB6B4924),
    ("BLISTA", 0xEB70965F),
    ("BLISTA2", 0x3DEE5EDA),
    ("BLISTA3", 0xDCBC1C3B),
    ("BMX", 0x43779C54),
    ("BOATTRAILER", 0x1F3D44B5),
    ("BOBCATXL", 0x3FC5D440),
    ("BODHI2", 0xAA699BB6),
    ("BOXVILLE", 0x898ECCEA),
    ("BOXVILLE2", 0xF21B33BE),
    ("BOXVILLE3", 0x07405E08),
    ("BOXVILLE4", 0x1A79847A),
    ("BRAWLER", 0xA7CE1BC5),
    ("BTYPE", 0x06FF6914),
    ("BTYPE2", 0xCE6B35A4),
    ("BUCCANEER", 0xD756460C),
    ("BUCCANEER2", 0xC397F748),
    ("BUFFALO", 0xEDD516C6),
    ("BUFFALO2", 0x2BEC3CBE),
    ("BUFFALO3", 0xE2C013E),
    ("BULLDOZER", 0x7074F39D),
    ("BULLET", 0x9AE6DDA1),
    ("BURRITO", 0xAFBB2CA4),
    ("BURRITO2", 0xC9E8FF76),
    ("BURRITO3", 0x98171BD3),
    ("BURRITO4", 0x353B561D),
    ("BURRITO5", 0x437CF2A0),
    ("BUS", 0xD577C962),
    ("BUZZARD", 0x2F03547B),
    ("BUZZARD2", 0x2C75F0DD),
    ("CABLECAR", 0xC6C3242D),
    ("CADDY", 0x44623884),
    ("CADDY2", 0xDFF0594C),
    ("CAMPER", 0x6FD95F68),
    ("CARBONIZZARE", 0x7B8AB45F),
    ("CARBONRS", 0x00ABB0C0),
    ("CARGOBOB", 0xFCFCB68B),
    ("CARGOBOB2", 0x60A7EA10),
    ("CARGOBOB3", 0x53174EEF),
    ("CARGOPLANE", 0x15F27762),
    ("CASCO", 0x3822BDFE),
    ("CAVALCADE", 0x779F23AA),
    ("CAVALCADE2", 0xD0EB2BE5),
    ("CHEETAH", 0xB1D95DA0),
    ("CHINO", 0x14D69010),
    ("CHINO2", 0xAED64A63),
    ("COACH", 0x84718D34),
    ("COGCABRIO", 0x13B57D8A),
    ("COMET2", 0xC1AE4D16),
    ("COQUETTE", 0x067BC037),
    ("COQUETTE2", 0x3C4E2113),
    ("COQUETTE3", 0x2EC385FE),
    ("CRUISER", 0x1ABA13B5),
    ("CRUSADER", 0x132D5A1A),
    ("CUBAN800", 0xD9927FE3),
    ("CUTTER", 0xC3FBA120),
    ("DAEMON", 0x77934CEE),
    ("DILETTANTE", 0xBC993509),
    ("DILETTANTE2", 0x64430650),
    ("DINGHY", 0x3D961290),
    ("DINGHY2", 0x107F392C),
    ("DINGHY3", 0x1E5E54EA),
    ("DLOADER", 0x698521E3),
    ("DOCKTRAILER", 0x806EFBEE),
    ("DOCKTUG", 0xCB44B1CA),
    ("DODO", 0xCA495705),
    ("DOMINATOR", 0x04CE68AC),
    ("DOMINATOR2", 0xC96B73D9),
    ("DOUBLE", 0x9C669788),
    ("DUBSTA", 0x462FE277),
    ("DUBSTA2", 0xE882E5F6),
    ("DUBSTA3", 0xB6410173),
    ("DUKES", 0x2B26F456),
    ("DUKES2", 0xEC8F7094),
    ("DUMP", 0x810369E2),
    ("DUNE", 0x9CF21E0F),
    ("DUNE2", 0x1FD824AF),
    ("DUSTER", 0x39D6779E),
    ("ELEGY2", 0xDE3D9D22),
    ("EMPEROR", 0xD7278283),
    ("EMPEROR2", 0x8FC3AADC),
    ("EMPEROR3", 0xB5FCF74E),
    ("ENDURO", 0x6882FA73),
    ("ENTITYXF", 0xB2FE5CF9),
    ("EXEMPLAR", 0xFFB15B5E),
    ("F620", 0xDCBCBE48),
    ("FACTION", 0x81A9CDDF),
    ("FACTION2", 0x95466BDB),
    ("FAGGIO2", 0x0350D1AB),
    ("FBI", 0x432EA949),
    ("FBI2", 0x9DC66994),
    ("FELON", 0xE8A8BDA8),
    ("FELON2", 0xFAAD85EE),
    ("FELTZER2", 0x8911B9F5),
    ("FELTZER3", 0xA29D6D10),
    ("FIRETRUK", 0x73920F8E),
    ("FIXTER", 0xCE23D3BF),
    ("FLATBED", 0x50B0215A),
    ("FORKLIFT", 0x58E49664),
    ("FQ2", 0xBC32A33B),
    ("FREIGHT", 0x3D6AAA9B),
    ("FREIGHTCAR", 0x0AFD22A6),
    ("FREIGHTCONT1", 0x36DCFF98),
    ("FREIGHTCONT2", 0x0E512E79),
    ("FREIGHTGRAIN", 0x264D9262),
    ("FREIGHTTRAILER", 0xD1ABB666),
    ("FROGGER", 0x2C634FBD),
    ("FROGGER2", 0x742E9AC0),
    ("FUGITIVE", 0x71CB2FFB),
    ("FUROREGT", 0xBF1691E0),
    ("FUSILADE", 0x1DC0BA53),
    ("FUTO", 0x7836CE2F),
    ("GAUNTLET", 0x94B395C5),
    ("GAUNTLET2", 0x14D22159),
    ("GBURRITO", 0x97FA4F36),
    ("GBURRITO2", 0x11AA0E14),
    ("GLENDALE", 0x047A6BC1),
    ("GRAINTRAILER", 0x3CC7F596),
    ("GRANGER", 0x9628879C),
    ("GRESLEY", 0xA3FC0F4D),
    ("GUARDIAN", 0x825A9F4C),
    ("HABANERO", 0x34B7390F),
    ("HAKUCHOU", 0x4B6C568A),
    ("HANDLER", 0x1A7FCEFA),
    ("HAULER", 0x5A82F9AE),
    ("HEXER", 0x11F76C14),
    ("HOTKNIFE", 0x0239E390),
    ("HUNTLEY", 0x1D06D681),
    ("HYDRA", 0x39D6E83F),
    ("INFERNUS", 0x18F25AC7),
    ("INGOT", 0xB3206692),
    ("INNOVATION", 0xF683EACA),
    ("INSURGENT", 0x9114EADA),
    ("INSURGENT2", 0x7B7E56F0),
    ("INTRUDER", 0x34DD8AA1),
    ("ISSI2", 0xB9CB3B69),
    ("JACKAL", 0xDAC67112),
    ("JB700", 0x3EAB5555),
    ("JESTER", 0xB2A716A3),
    ("JESTER2", 0xBE0E6126),
    ("JET", 0x3F119114),
    ("JETMAX", 0x33581161),
    ("JOURNEY", 0xF8D48E7A),
    ("KALAHARI", 0x05852838),
    ("KHAMELION", 0x206D1B68),
    ("KURUMA", 0xAE2BFE94),
    ("KURUMA2", 0x187D938D),
    ("LANDSTALKER", 0x4BA4E8DC),
    ("LAZER", 0xB39B0AE6),
    ("LECTRO", 0x26321E67),
    ("LGUARD", 0x1BF8D381),
    ("LURCHER", 0x7B47A6A7),
    ("LUXOR", 0x250B0C5E),
    ("LUXOR2", 0xB79F589E),
    ("MAMMATUS", 0x97E55D11),
    ("MANANA", 0x81634188),
    ("MARQUIS", 0xC1CE1183),
    ("MARSHALL", 0x49863E9C),
    ("MASSACRO", 0xF77ADE32),
    ("MASSACRO2", 0xDA5819A3),
    ("MAVERICK", 0x9D0450CA),
    ("MESA", 0x36848602),
    ("MESA2", 0xD36A4B44),
    ("MESA3", 0x84F42E51),
    ("METROTRAIN", 0x33C9E158),
    ("MILJET", 0x09D80F93),
    ("MINIVAN", 0xED7EADA4),
    ("MIXER", 0xD138A6BB),
    ("MIXER2", 0x1C534995),
    ("MONROE", 0xE62B361B),
    ("MONSTER", 0xCD93A7DB),
    ("MOONBEAM", 0x1F52A43F),
    ("MOONBEAM2", 0x710A2B9B),
    ("MOWER", 0x6A4BD8F6),
    ("MULE", 0x35ED670B),
    ("MULE2", 0xC1632BEB),
    ("MULE3", 0x85A5B471),
    ("NEMESIS", 0xDA288376),
    ("NINEF", 0x3D8FA25C),
    ("NINEF2", 0xA8E38B01),
    ("ORACLE", 0x506434F6),
    ("ORACLE2", 0xE18195B2),
    ("OSIRIS", 0x767164D6),
    ("PACKER", 0x21EEE87D),
    ("PANTO", 0xE644E480),
    ("PARADISE", 0x58B3979C),
    ("PATRIOT", 0xCFCFEB3B),
    ("PBUS", 0x885F3671),
    ("PCJ", 0xC9CEAF06),
    ("PENUMBRA", 0xE9805550),
    ("PEYOTE", 0x6D19CCBC),
    ("PHANTOM", 0x809AA4CB),
    ("PHOENIX", 0x831A21D5),
    ("PICADOR", 0x59E0FBF3),
    ("PIGALLE", 0x404B6381),
    ("POLICE", 0x79FBB0C5),
    ("POLICE2", 0x9F05F101),
    ("POLICE3", 0x71FA16EA),
    ("POLICE4", 0x8A63C7B9),
    ("POLICEB", 0xFDEFAEC3),
    ("POLICEOLD1", 0xA46462F7),
    ("POLICEOLD2", 0x95F4C618),
    ("POLICET", 0x1B38E955),
    ("POLMAV", 0x1517D4D9),
    ("PONY", 0xF8DE29A8),
    ("PONY2", 0x38408341),
    ("POUNDER", 0x7DE35E7D),
    ("PRAIRIE", 0xA988D3A2),
    ("PRANGER", 0x2C33B46E),
    ("PREDATOR", 0xE2E7D4AB),
    ("PREMIER", 0x8FB66F9B),
    ("PRIMO", 0xBB6B404F),
    ("PRIMO2", 0x86618EDA),
    ("PROPTRAILER", 0x153E1B0A),
    ("RADI", 0x9D96B45B),
    ("RAKETRAILER", 0x174CB172),
    ("RANCHERXL", 0x6210CBB0),
    ("RANCHERXL2", 0x7341576B),
    ("RAPIDGT", 0x8CB29A14),
    ("RAPIDGT2", 0x679450AF),
    ("RATLOADER", 0xD83C13CE),
    ("RATLOADER2", 0xDCE1D9F7),
    ("REBEL", 0xB802DD46),
    ("REBEL2", 0x8612B64B),
    ("REGINA", 0xFF22D208),
    ("RENTALBUS", 0xBE819C63),
    ("RHAPSODY", 0x322CF98F),
    ("RHINO", 0x2EA68690),
    ("RIOT", 0xB822A1AA),
    ("RIPLEY", 0xCD935EF9),
    ("ROCOTO", 0x7F5C91F1),
    ("ROMERO", 0x2560B2FC),
    ("RUBBLE", 0x9A5B1DCC),
    ("RUFFIAN", 0xCABD11E8),
    ("RUINER", 0xF26CEFF9),
    ("RUMPO", 0x4543B74D),
    ("RUMPO2", 0x961AFEF7),
    ("SABREGT", 0x9B909C94),
    ("SADLER", 0xDC434E51),
    ("SADLER2", 0x2BC345D1),
    ("SANCHEZ", 0x2EF89E46),
    ("SANCHEZ2", 0xA960B13E),
    ("SANDKING", 0xB9210FD0),
    ("SANDKING2", 0x3AF8C345),
    ("SAVAGE", 0xFB133A17),
    ("SCHAFTER2", 0xB52B5113),
    ("SCHWARZER", 0xD37B7976),
    ("SCORCHER", 0xF4E1AA15),
    ("SCRAP", 0x9A9FD3DF),
    ("SEASHARK", 0xC2974024),
    ("SEASHARK2", 0xDB4388E4),
    ("SEMINOLE", 0x48CECED3),
    ("SENTINEL", 0x50732C82),
    ("SENTINEL2", 0x3412AE2D),
    ("SERRANO", 0x4FB1A214),
    ("SHAMAL", 0xB79C1BF5),
    ("SHERIFF", 0x9BAA707C),
    ("SHERIFF2", 0x72935408),
    ("SKYLIFT", 0x3E48BF23),
    ("SLAMVAN", 0x2B7F9DE3),
    ("SLAMVAN2", 0x31ADBBFC),
    ("SOVEREIGN", 0x2C509634),
    ("SPEEDER", 0x0DC60D2B),
    ("SPEEDO", 0xCFB3870C),
    ("SPEEDO2", 0x2B6DC64A),
    ("SQUALO", 0x17DF5EC2),
    ("STALION", 0x72A4C31E),
    ("STALION2", 0xE80F67EE),
    ("STANIER", 0xA7EDE74D),
    ("STINGER", 0x5C23AF9B),
    ("STINGERGT", 0x82E499FA),
    ("STOCKADE", 0x6827CF72),
    ("STOCKADE3", 0xF337AB36),
    ("STRATUM", 0x66B4FC45),
    ("STRETCH", 0x8B13F083),
    ("STUNT", 0x81794C70),
    ("SUBMERSIBLE", 0x2DFF622F),
    ("SUBMERSIBLE2", 0xC07107EE),
    ("SULTAN", 0x39DA2754),
    ("SUNTRAP", 0xEF2295C9),
    ("SUPERD", 0x42F2ED16),
    ("SURANO", 0x16E478C1),
    ("SURFER", 0x29B0DA97),
    ("SURFER2", 0xB1D80E06),
    ("SURGE", 0x8F0E3594),
    ("SWIFT", 0xEBC24DF2),
    ("SWIFT2", 0x4019CB4C),
    ("T20", 0x6322B39A),
    ("TACO", 0x744CA80D),
    ("TAILGATER", 0xC3DDFDCE),
    ("TANKER", 0xD46F4737),
    ("TANKER2", 0x74998082),
    ("TANKERCAR", 0x22EDDC30),
    ("TAXI", 0xC703DB5F),
    ("TECHNICAL", 0x83051506),
    ("THRUST", 0x6D6F8F43),
    ("TIPTRUCK", 0x02E19879),
    ("TIPTRUCK2", 0xC7824E5E),
    ("TITAN", 0x761E2AD3),
    ("TORO", 0x3FD5AA2F),
    ("TORNADO", 0x1BB290BC),
    ("TORNADO2", 0x5B42A5C4),
    ("TORNADO3", 0x690A4153),
    ("TORNADO4", 0x86CF7CDD),
    ("TOURBUS", 0x73B1C3CB),
    ("TOWTRUCK", 0xB12314E0),
    ("TOWTRUCK2", 0xE5A2D6C6),
    ("TR2", 0x7BE032C6),
    ("TR3", 0x6A59902D),
    ("TR4", 0x7CAB34D0),
    ("TRACTOR", 0x61D6BA8C),
    ("TRACTOR2", 0x843B73DE),
    ("TRACTOR3", 0x562A97BD),
    ("TRAILERLOGS", 0x782A236D),
    ("TRAILERS", 0xCBB2BE0E),
    ("TRAILERS2", 0xA1DA3C91),
    ("TRAILERS3", 0x8548036D),
    ("TRAILERSMALL", 0x2A72BEAB),
    ("TRASH", 0x72435A19),
    ("TRASH2", 0xB527915C),
    ("TRFLAT", 0xAF62F6B2),
    ("TRIBIKE", 0x4339CD69),
    ("TRIBIKE2", 0xB67597EC),
    ("TRIBIKE3", 0xE823FB48),
    ("TROPIC", 0x1149422F),
    ("TURISMOR", 0x185484E1),
    ("TVTRAILER", 0x967620BE),
    ("UTILLITRUCK", 0x1ED0A534),
    ("UTILLITRUCK2", 0x34E6BF6B),
    ("UTILLITRUCK3", 0x7F2153DF),
    ("VACCA", 0x142E0DC3),
    ("VADER", 0xF79A00F7),
    ("VALKYRIE", 0xA09E15FD),
    ("VELUM", 0x9C429B6A),
    ("VELUM2", 0x403820E8),
    ("VESTRA", 0x4FF77E37),
    ("VIGERO", 0xCEC6B9B7),
    ("VINDICATOR", 0xAF599F01),
    ("VIRGO", 0xE2504942),
    ("VOLTIC", 0x9F4B77BE),
    ("VOODOO", 0x779B4F2D),
    ("VOODOO2", 0x1F3766E3),
    ("WARRENER", 0x51D83328),
    ("WASHINGTON", 0x69F06B57),
    ("WINDSOR", 0x5E4327C8),
    ("YOUGA", 0x03E5F6B8),
    ("ZENTORNO", 0xAC5DF515),
    ("ZION", 0xBD1B39C3),
    ("ZION2", 0xB8E2AE18),
)


# 角色模型
PLAYER_MODEL = (
    ("MICHAEL 麦克", "player_zero"),
    ("FRANKLIN 富兰克林", "player_one"),
    ("TREVOR 催佛", "player_two"),
    ("BOAR 野猪", "a_c_boar"),
    ("CHIMP 黑猩猩", "a_c_chimp"),
    ("COW 牛", "a_c_cow"),
    ("COYOTE 郊狼", "a_c_coyote"),
    ("DEER 鹿", "a_c_deer"),
    ("FISH 鱼", "a_c_fish"),
    ("HEN 母鸡", "a_c_hen"),
    ("CAT 猫", "a_c_cat_01"),
    ("HAWK 鹰", "a_c_chickenhawk"),
    ("CORMORANT 鸬鹚", "a_c_cormorant"),
    ("CROW 乌鸦", "a_c_crow"),
    ("DOLPHIN 海豚", "a_c_dolphin"),
    ("HUMPBACK 驼背鲸", "a_c_humpback"),
    ("WHALE 鲸鱼", "a_c_killerwhale"),
    ("PIGEON 鸽子", "a_c_pigeon"),
    ("SEAGULL 海鸥", "a_c_seagull"),
    ("SHARKHAMMER 鲨鱼", "a_c_sharkhammer"),
    ("PIG 猪", "a_c_pig"),
    ("RAT 大鼠", "a_c_rat"),
    ("RHESUS 猕猴", "a_c_rhesus"),
    ("CHOP 印章", "a_c_chop"),
    ("HUSKY 哈士奇", "a_c_husky"),
    ("MTLION", "a_c_mtlion"),
    ("RETRIEVER 猎犬", "a_c_retriever"),
    ("SHARKTIGER sharktiger", "a_c_sharktiger"),
    ("SHEPHERD 牧羊人", "a_c_shepherd"),
    ("ALIEN 外星人", "s_m_m_movalien_01"),
    ("BEACH 海滩比基尼女孩", "a_f_m_beach_01"),
    ("BEVHILLS", "a_f_m_bevhills_01"),
    ("BEVHILLS", "a_f_m_bevhills_02"),
    ("BODYBUILD", "a_f_m_bodybuild_01"),
    ("BUSINESS", "a_f_m_business_02"),
    ("DOWNTOWN", "a_f_m_downtown_01"),
    ("EASTSA", "a_f_m_eastsa_01"),
    ("EASTSA", "a_f_m_eastsa_02"),
    ("FATBLA", "a_f_m_fatbla_01"),
    ("FATCULT", "a_f_m_fatcult_01"),
    ("FATWHITE", "a_f_m_fatwhite_01"),
    ("KTOWN", "a_f_m_ktown_01"),
    ("KTOWN", "a_f_m_ktown_02"),
    ("PROLHOST", "a_f_m_prolhost_01"),
    ("SALTON", "a_f_m_salton_01"),
    ("SKIDROW", "a_f_m_skidrow_01"),
    ("SOUCENTMC", "a_f_m_soucentmc_01"),
    ("SOUCENT", "a_f_m_soucent_01"),
    ("SOUCENT", "a_f_m_soucent_02"),
    ("TOURIST", "a_f_m_tourist_01"),
    ("TRAMPBEAC", "a_f_m_trampbeac_01"),
    ("TRAMP", "a_f_m_tramp_01"),
    ("GENSTREET", "a_f_o_genstreet_01"),
    ("INDIAN 印度", "a_f_o_indian_01"),
    ("KTOWN", "a_f_o_ktown_01"),
    ("SALTON", "a_f_o_salton_01"),
    ("SOUCENT", "a_f_o_soucent_01"),
    ("SOUCENT", "a_f_o_soucent_02"),
    ("BEACH 海滩女孩", "a_f_y_beach_01"),
    ("BEVHILLS", "a_f_y_bevhills_01"),
    ("BEVHILLS", "a_f_y_bevhills_02"),
    ("BEVHILLS", "a_f_y_bevhills_03"),
    ("BEVHILLS", "a_f_y_bevhills_04"),
    ("BUSINESS", "a_f_y_business_01"),
    ("BUSINESS", "a_f_y_business_02"),
    ("BUSINESS", "a_f_y_business_03"),
    ("BUSINESS", "a_f_y_business_04"),
    ("EASTSA", "a_f_y_eastsa_01"),
    ("EASTSA", "a_f_y_eastsa_02"),
    ("EASTSA", "a_f_y_eastsa_03"),
    ("EPSILON", "a_f_y_epsilon_01"),
    ("FITNESS 健身", "a_f_y_fitness_01"),
    ("FITNESS 健身", "a_f_y_fitness_02"),
    ("GENHOT", "a_f_y_genhot_01"),
    ("GOLFER 高尔夫球手", "a_f_y_golfer_01"),
    ("HIKER 徒步旅行者", "a_f_y_hiker_01"),
    ("HIPPIE", "a_f_y_hippie_01"),
    ("HIPSTER 赶时髦的人", "a_f_y_hipster_01"),
    ("HIPSTER 赶时髦的人", "a_f_y_hipster_02"),
    ("HIPSTER 赶时髦的人", "a_f_y_hipster_03"),
    ("HIPSTER 赶时髦的人", "a_f_y_hipster_04"),
    ("INDIAN 印度", "a_f_y_indian_01"),
    ("JUGGALO", "a_f_y_juggalo_01"),
    ("RUNNER 转轮", "a_f_y_runner_01"),
    ("RURMETH", "a_f_y_rurmeth_01"),
    ("SCDRESSY", "a_f_y_scdressy_01"),
    ("SKATER 滑冰者", "a_f_y_skater_01"),
    ("SOUCENT", "a_f_y_soucent_01"),
    ("SOUCENT", "a_f_y_soucent_02"),
    ("SOUCENT", "a_f_y_soucent_03"),
    ("TENNIS 网球", "a_f_y_tennis_01"),
    ("TOPLESS 袒胸", "a_f_y_topless_01"),
    ("TOURIST 旅游", "a_f_y_tourist_01"),
    ("TOURIST 旅游", "a_f_y_tourist_02"),
    ("VINEWOOD", "a_f_y_vinewood_01"),
    ("VINEWOOD", "a_f_y_vinewood_02"),
    ("VINEWOOD", "a_f_y_vinewood_03"),
    ("VINEWOOD", "a_f_y_vinewood_04"),
    ("YOGA 瑜伽", "a_f_y_yoga_01"),
    ("ACULT 急性", "a_m_m_acult_01"),
    ("AFRIAMER", "a_m_m_afriamer_01"),
    ("BEACH 海滩", "a_m_m_beach_01"),
    ("BEACH 海滩", "a_m_m_beach_02"),
    ("BEVHILLS", "a_m_m_bevhills_01"),
    ("BEVHILLS", "a_m_m_bevhills_02"),
    ("BUSINESS 业务", "a_m_m_business_01"),
    ("EASTSA", "a_m_m_eastsa_01"),
    ("EASTSA", "a_m_m_eastsa_02"),
    ("FARMER 农民", "a_m_m_farmer_01"),
    ("FATLATIN", "a_m_m_fatlatin_01"),
    ("GENFAT", "a_m_m_genfat_01"),
    ("GENFAT", "a_m_m_genfat_02"),
    ("GOLFER 高尔夫球手", "a_m_m_golfer_01"),
    ("HASJEW", "a_m_m_hasjew_01"),
    ("HILLBILLY 乡下人", "a_m_m_hillbilly_01"),
    ("HILLBILLY 乡下人", "a_m_m_hillbilly_02"),
    ("INDIAN 印度", "a_m_m_indian_01"),
    ("KTOWN KTown", "a_m_m_ktown_01"),
    ("MALIBU 马里布", "a_m_m_malibu_01"),
    ("MEXCNTRY", "a_m_m_mexcntry_01"),
    ("MEXLABOR", "a_m_m_mexlabor_01"),
    ("OG_BOSS", "a_m_m_og_boss_01"),
    ("PAPARAZZI 狗仔队", "a_m_m_paparazzi_01"),
    ("POLYNESIAN 波利尼西亚", "a_m_m_polynesian_01"),
    ("PROLHOST", "a_m_m_prolhost_01"),
    ("RURMETH", "a_m_m_rurmeth_01"),
    ("SALTON 索尔顿", "a_m_m_salton_01"),
    ("SALTON 索尔顿", "a_m_m_salton_02"),
    ("SALTON 索尔顿", "a_m_m_salton_03"),
    ("SALTON 索尔顿", "a_m_m_salton_04"),
    ("SKATER 滑冰者", "a_m_m_skater_01"),
    ("SKIDROW 密技", "a_m_m_skidrow_01"),
    ("SOCENLAT", "a_m_m_socenlat_01"),
    ("SOUCENT", "a_m_m_soucent_01"),
    ("SOUCENT", "a_m_m_soucent_02"),
    ("SOUCENT", "a_m_m_soucent_03"),
    ("SOUCENT", "a_m_m_soucent_04"),
    ("STLAT", "a_m_m_stlat_02"),
    ("TENNIS 网球", "a_m_m_tennis_01"),
    ("TOURIST 旅游", "a_m_m_tourist_01"),
    ("TRAMPBEAC", "a_m_m_trampbeac_01"),
    ("TRAMP 流浪汉", "a_m_m_tramp_01"),
    ("TRANVEST", "a_m_m_tranvest_01"),
    ("TRANVEST", "a_m_m_tranvest_02"),
    ("ACULT 急性", "a_m_o_acult_01"),
    ("ACULT 急性", "a_m_o_acult_02"),
    ("BEACH 海滩", "a_m_o_beach_01"),
    ("GENSTREET", "a_m_o_genstreet_01"),
    ("KTOWN KTown", "a_m_o_ktown_01"),
    ("SALTON 索尔顿", "a_m_o_salton_01"),
    ("SOUCENT", "a_m_o_soucent_01"),
    ("SOUCENT", "a_m_o_soucent_02"),
    ("SOUCENT", "a_m_o_soucent_03"),
    ("TRAMP 流浪汉", "a_m_o_tramp_01"),
    ("ACULT 急性", "a_m_y_acult_01"),
    ("ACULT 急性", "a_m_y_acult_02"),
    ("BEACHVESP", "a_m_y_beachvesp_01"),
    ("BEACHVESP", "a_m_y_beachvesp_02"),
    ("BEACH 海滩", "a_m_y_beach_01"),
    ("BEACH 海滩", "a_m_y_beach_02"),
    ("BEACH 海滩", "a_m_y_beach_03"),
    ("BEVHILLS", "a_m_y_bevhills_01"),
    ("BEVHILLS", "a_m_y_bevhills_02"),
    ("BREAKDANCE 霹雳舞", "a_m_y_breakdance_01"),
    ("BUSICAS", "a_m_y_busicas_01"),
    ("BUSINESS 业务", "a_m_y_business_01"),
    ("BUSINESS 业务", "a_m_y_business_02"),
    ("BUSINESS 业务", "a_m_y_business_03"),
    ("CYCLIST 骑自行车的人", "a_m_y_cyclist_01"),
    ("DHILL", "a_m_y_dhill_01"),
    ("DOWNTOWN 市中心", "a_m_y_downtown_01"),
    ("EASTSA", "a_m_y_eastsa_01"),
    ("EASTSA", "a_m_y_eastsa_02"),
    ("EPSILON", "a_m_y_epsilon_01"),
    ("EPSILON", "a_m_y_epsilon_02"),
    ("GAY", "a_m_y_gay_01"),
    ("GAY", "a_m_y_gay_02"),
    ("GENSTREET", "a_m_y_genstreet_01"),
    ("GENSTREET", "a_m_y_genstreet_02"),
    ("GOLFER 高尔夫球手", "a_m_y_golfer_01"),
    ("HASJEW", "a_m_y_hasjew_01"),
    ("HIKER 徒步旅行者", "a_m_y_hiker_01"),
    ("HIPPY", "a_m_y_hippy_01"),
    ("HIPSTER 赶时髦的人", "a_m_y_hipster_01"),
    ("HIPSTER 赶时髦的人", "a_m_y_hipster_02"),
    ("HIPSTER 赶时髦的人", "a_m_y_hipster_03"),
    ("INDIAN 印度", "a_m_y_indian_01"),
    ("JETSKI 喷气滑雪", "a_m_y_jetski_01"),
    ("JUGGALO", "a_m_y_juggalo_01"),
    ("KTOWN KTown", "a_m_y_ktown_01"),
    ("KTOWN KTown", "a_m_y_ktown_02"),
    ("LATINO 拉丁美洲人", "a_m_y_latino_01"),
    ("METHHEAD", "a_m_y_methhead_01"),
    ("MEXTHUG", "a_m_y_mexthug_01"),
    ("MOTOX MotoX", "a_m_y_motox_01"),
    ("MOTOX MotoX", "a_m_y_motox_02"),
    ("MUSCLBEAC", "a_m_y_musclbeac_01"),
    ("MUSCLBEAC", "a_m_y_musclbeac_02"),
    ("POLYNESIAN 波利尼西亚", "a_m_y_polynesian_01"),
    ("ROADCYC", "a_m_y_roadcyc_01"),
    ("RUNNER 转轮", "a_m_y_runner_01"),
    ("RUNNER 转轮", "a_m_y_runner_02"),
    ("SALTON 索尔顿", "a_m_y_salton_01"),
    ("SKATER 滑冰者", "a_m_y_skater_01"),
    ("SKATER 滑冰者", "a_m_y_skater_02"),
    ("SOUCENT", "a_m_y_soucent_01"),
    ("SOUCENT", "a_m_y_soucent_02"),
    ("SOUCENT", "a_m_y_soucent_03"),
    ("SOUCENT", "a_m_y_soucent_04"),
    ("STBLA", "a_m_y_stbla_01"),
    ("STBLA", "a_m_y_stbla_02"),
    ("STLAT", "a_m_y_stlat_01"),
    ("STWHI", "a_m_y_stwhi_01"),
    ("STWHI", "a_m_y_stwhi_02"),
    ("SUNBATHE 日光浴", "a_m_y_sunbathe_01"),
    ("SURFER 冲浪者", "a_m_y_surfer_01"),
    ("VINDOUCHE", "a_m_y_vindouche_01"),
    ("VINEWOOD", "a_m_y_vinewood_01"),
    ("VINEWOOD", "a_m_y_vinewood_02"),
    ("VINEWOOD", "a_m_y_vinewood_03"),
    ("VINEWOOD", "a_m_y_vinewood_04"),
    ("YOGA 瑜伽", "a_m_y_yoga_01"),
    ("PROLDRIVER", "u_m_y_proldriver_01"),
    ("RSRANGER", "u_m_y_rsranger_01"),
    ("SBIKE", "u_m_y_sbike"),
    ("STAGGRM", "u_m_y_staggrm_01"),
    ("TATTOO 纹身", "u_m_y_tattoo_01"),
    ("ABIGAIL 阿比盖尔", "csb_abigail"),
    ("ANITA 安妮塔", "csb_anita"),
    ("ANTON 安东", "csb_anton"),
    ("BALLASOG", "csb_ballasog"),
    ("BRIDE 新娘", "csb_bride"),
    ("BURGERDRUG", "csb_burgerdrug"),
    ("CAR3GUY1 car3guy1", "csb_car3guy1"),
    ("CAR3GUY2 car3guy2", "csb_car3guy2"),
    ("CHEF 厨师", "csb_chef"),
    ("CHIN_GOON", "csb_chin_goon"),
    ("CLETUS 克雷斯", "csb_cletus"),
    ("COP 警察", "csb_cop"),
    ("CUSTOMER 客户", "csb_customer"),
    ("DENISE_FRIEND", "csb_denise_friend"),
    ("FOS_REP", "csb_fos_rep"),
    ("G G", "csb_g"),
    ("GROOM 新郎", "csb_groom"),
    ("DLR DLR", "csb_grove_str_dlr"),
    ("HAO 浩", "csb_hao"),
    ("HUGH 休米", "csb_hugh"),
    ("IMRAN 伊姆兰", "csb_imran"),
    ("JANITOR 看门人", "csb_janitor"),
    ("MAUDE 莫德", "csb_maude"),
    ("MWEATHER", "csb_mweather"),
    ("ORTEGA 奥尔特加", "csb_ortega"),
    ("OSCAR 奥斯卡", "csb_oscar"),
    ("PORNDUDES", "csb_porndudes"),
    ("PORNDUDES_P", "csb_porndudes_p"),
    ("PROLOGUEDRIVER", "csb_prologuedriver"),
    ("PROLSEC", "csb_prolsec"),
    ("GANG 岗", "csb_ramp_gang"),
    ("HIC HIC", "csb_ramp_hic"),
    ("HIPSTER 赶时髦的人", "csb_ramp_hipster"),
    ("MARINE", "csb_ramp_marine"),
    ("MEX 墨西哥", "csb_ramp_mex"),
    ("REPORTER 记者", "csb_reporter"),
    ("ROCCOPELOSI", "csb_roccopelosi"),
    ("SCREEN_WRITER", "csb_screen_writer"),
    ("STRIPPER 脱衣舞女", "csb_stripper_01"),
    ("STRIPPER 脱衣舞女", "csb_stripper_02"),
    ("TONYA 谭雅", "csb_tonya"),
    ("TRAFFICWARDEN 交通管理员", "csb_trafficwarden"),
    ("AMANDATOWNLEY", "cs_amandatownley"),
    ("ANDREAS 安德烈亚斯", "cs_andreas"),
    ("ASHLEY 艾希礼", "cs_ashley"),
    ("BANKMAN 阶段采掘工", "cs_bankman"),
    ("BARRY 巴里", "cs_barry"),
    ("BARRY_P", "cs_barry_p"),
    ("BEVERLY 贝弗利", "cs_beverly"),
    ("BEVERLY_P", "cs_beverly_p"),
    ("BRAD 布拉德", "cs_brad"),
    ("BRADCADAVER", "cs_bradcadaver"),
    ("CARBUYER", "cs_carbuyer"),
    ("CASEY 凯西", "cs_casey"),
    ("CHENGSR", "cs_chengsr"),
    ("CHRISFORMAGE", "cs_chrisformage"),
    ("CLAY 粘土", "cs_clay"),
    ("DALE 山谷", "cs_dale"),
    ("DAVENORTON", "cs_davenorton"),
    ("DEBRA 黛布拉", "cs_debra"),
    ("DENISE 丹妮丝", "cs_denise"),
    ("DEVIN 德文", "cs_devin"),
    ("DOM DOM", "cs_dom"),
    ("DREYFUSS 德莱弗斯", "cs_dreyfuss"),
    ("DRFRIEDLANDER", "cs_drfriedlander"),
    ("FABIEN 法比安", "cs_fabien"),
    ("FBISUIT", "cs_fbisuit_01"),
    ("FLOYD 弗洛依德", "cs_floyd"),
    ("GUADALOPE 瓜达洛普山", "cs_guadalope"),
    ("GURK 打嗝", "cs_gurk"),
    ("HUNTER 猎人", "cs_hunter"),
    ("JANET 珍妮特", "cs_janet"),
    ("JEWELASS", "cs_jewelass"),
    ("JIMMYBOSTON", "cs_jimmyboston"),
    ("JIMMYDISANTO", "cs_jimmydisanto"),
    ("JOEMINUTEMAN", "cs_joeminuteman"),
    ("JOHNNYKLEBITZ", "cs_johnnyklebitz"),
    ("JOSEF 约瑟夫", "cs_josef"),
    ("JOSH 杰克", "cs_josh"),
    ("LAMARDAVIS", "cs_lamardavis"),
    ("LAZLOW", "cs_lazlow"),
    ("LESTERCREST", "cs_lestercrest"),
    ("LIFEINVAD", "cs_lifeinvad_01"),
    ("MAGENTA", "cs_magenta"),
    ("MANUEL 曼努埃尔", "cs_manuel"),
    ("MARNIE 玛妮", "cs_marnie"),
    ("MARTINMADRAZO", "cs_martinmadrazo"),
    ("MARYANN 玛丽安", "cs_maryann"),
    ("MICHELLE 米歇尔", "cs_michelle"),
    ("MILTON 密尔顿", "cs_milton"),
    ("MOLLY 莫莉", "cs_molly"),
    ("MOVPREMF", "cs_movpremf_01"),
    ("MOVPREMMALE", "cs_movpremmale"),
    ("MRK MRK", "cs_mrk"),
    ("MRSPHILLIPS", "cs_mrsphillips"),
    ("MRS_THORNHILL", "cs_mrs_thornhill"),
    ("NATALIA 娜塔莉亚", "cs_natalia"),
    ("NERVOUSRON", "cs_nervousron"),
    ("NIGEL 奈吉尔", "cs_nigel"),
    ("OLD_MAN1A", "cs_old_man1a"),
    ("OLD_MAN2", "cs_old_man2"),
    ("OMEGA 欧米茄", "cs_omega"),
    ("ORLEANS 奥尔良", "cs_orleans"),
    ("PAPER 纸", "cs_paper"),
    ("PAPER_P", "cs_paper_p"),
    ("PATRICIA 帕特丽夏", "cs_patricia"),
    ("PRIEST 牧师", "cs_priest"),
    ("PROLSEC", "cs_prolsec_02"),
    ("RUSSIANDRUNK", "cs_russiandrunk"),
    ("SIEMONYETARIAN", "cs_siemonyetarian"),
    ("SOLOMON 所罗门", "cs_solomon"),
    ("STEVEHAINS", "cs_stevehains"),
    ("STRETCH 拉伸", "cs_stretch"),
    ("TANISHA Tanisha", "cs_tanisha"),
    ("TAOCHENG 桃城", "cs_taocheng"),
    ("TAOSTRANSLATOR", "cs_taostranslator"),
    ("TENNISCOACH", "cs_tenniscoach"),
    ("TERRY 特里", "cs_terry"),
    ("TOM 汤姆", "cs_tom"),
    ("TOMEPSILON", "cs_tomepsilon"),
    ("TRACYDISANTO", "cs_tracydisanto"),
    ("WADE 韦德", "cs_wade"),
    ("ZIMBOR", "cs_zimbor"),
    ("BALLAS", "g_f_y_ballas_01"),
    ("FAMILIES 家庭", "g_f_y_families_01"),
    ("LOST 失落摩托帮", "g_f_y_lost_01"),
    ("VAGOS Vagos", "g_f_y_vagos_01"),
    ("ARMBOSS", "g_m_m_armboss_01"),
    ("ARMGOON", "g_m_m_armgoon_01"),
    ("ARMLIEUT", "g_m_m_armlieut_01"),
    ("CHEMWORK", "g_m_m_chemwork_01"),
    ("CHEMWORK_P", "g_m_m_chemwork_01_p"),
    ("CHIBOSS", "g_m_m_chiboss_01"),
    ("CHIBOSS_P", "g_m_m_chiboss_01_p"),
    ("CHICOLD", "g_m_m_chicold_01"),
    ("CHICOLD_P", "g_m_m_chicold_01_p"),
    ("CHIGOON", "g_m_m_chigoon_01"),
    ("CHIGOON_P", "g_m_m_chigoon_01_p"),
    ("CHIGOON", "g_m_m_chigoon_02"),
    ("KORBOSS", "g_m_m_korboss_01"),
    ("MEXBOSS", "g_m_m_mexboss_01"),
    ("MEXBOSS", "g_m_m_mexboss_02"),
    ("ARMGOON", "g_m_y_armgoon_02"),
    ("AZTECA 阿兹台克", "g_m_y_azteca_01"),
    ("BALLAEAST", "g_m_y_ballaeast_01"),
    ("BALLAORIG", "g_m_y_ballaorig_01"),
    ("BALLASOUT", "g_m_y_ballasout_01"),
    ("FAMCA", "g_m_y_famca_01"),
    ("FAMDNF", "g_m_y_famdnf_01"),
    ("FAMFOR", "g_m_y_famfor_01"),
    ("KOREAN 韩国人", "g_m_y_korean_01"),
    ("KOREAN 韩国人", "g_m_y_korean_02"),
    ("KORLIEUT", "g_m_y_korlieut_01"),
    ("LOST 失落摩托帮", "g_m_y_lost_01"),
    ("LOST 失落摩托帮", "g_m_y_lost_02"),
    ("LOST 失落摩托帮", "g_m_y_lost_03"),
    ("MEXGANG", "g_m_y_mexgang_01"),
    ("MEXGOON", "g_m_y_mexgoon_01"),
    ("MEXGOON", "g_m_y_mexgoon_02"),
    ("MEXGOON", "g_m_y_mexgoon_03"),
    ("MEXGOON_P", "g_m_y_mexgoon_03_p"),
    ("POLOGOON", "g_m_y_pologoon_01"),
    ("POLOGOON_P", "g_m_y_pologoon_01_p"),
    ("POLOGOON", "g_m_y_pologoon_02"),
    ("POLOGOON_P", "g_m_y_pologoon_02_p"),
    ("SALVABOSS", "g_m_y_salvaboss_01"),
    ("SALVAGOON", "g_m_y_salvagoon_01"),
    ("SALVAGOON", "g_m_y_salvagoon_02"),
    ("SALVAGOON", "g_m_y_salvagoon_03"),
    ("SALVAGOON_P", "g_m_y_salvagoon_03_p"),
    ("STRPUNK", "g_m_y_strpunk_01"),
    ("STRPUNK", "g_m_y_strpunk_02"),
    ("HC_DRIVER", "hc_driver"),
    ("HC_GUNMAN", "hc_gunman"),
    ("HC_HACKER", "hc_hacker"),
    ("ABIGAIL 阿比盖尔", "ig_abigail"),
    ("AMANDATOWNLEY", "ig_amandatownley"),
    ("ANDREAS 安德烈亚斯", "ig_andreas"),
    ("ASHLEY 艾希礼", "ig_ashley"),
    ("BALLASOG", "ig_ballasog"),
    ("BANKMAN 阶段采掘工", "ig_bankman"),
    ("BARRY 巴里", "ig_barry"),
    ("BARRY_P", "ig_barry_p"),
    ("BESTMEN 博仕", "ig_bestmen"),
    ("BEVERLY 贝弗利", "ig_beverly"),
    ("BEVERLY_P", "ig_beverly_p"),
    ("BRAD 布拉德", "ig_brad"),
    ("BRIDE 新娘", "ig_bride"),
    ("CAR3GUY1 car3guy1", "ig_car3guy1"),
    ("CAR3GUY2 car3guy2", "ig_car3guy2"),
    ("CASEY 凯西", "ig_casey"),
    ("CHEF 厨师", "ig_chef"),
    ("CHENGSR", "ig_chengsr"),
    ("CHRISFORMAGE", "ig_chrisformage"),
    ("CLAY 粘土", "ig_clay"),
    ("CLAYPAIN", "ig_claypain"),
    ("CLETUS 克雷斯", "ig_cletus"),
    ("DALE 山谷", "ig_dale"),
    ("DAVENORTON", "ig_davenorton"),
    ("DENISE 丹妮丝", "ig_denise"),
    ("DEVIN 德文", "ig_devin"),
    ("DOM DOM", "ig_dom"),
    ("DREYFUSS 德莱弗斯", "ig_dreyfuss"),
    ("DRFRIEDLANDER", "ig_drfriedlander"),
    ("FABIEN 法比安", "ig_fabien"),
    ("FBISUIT", "ig_fbisuit_01"),
    ("FLOYD 弗洛依德", "ig_floyd"),
    ("GROOM 新郎", "ig_groom"),
    ("HAO 浩", "ig_hao"),
    ("HUNTER 猎人", "ig_hunter"),
    ("JANET 珍妮特", "ig_janet"),
    ("JAY_NORRIS", "ig_jay_norris"),
    ("JEWELASS", "ig_jewelass"),
    ("JIMMYBOSTON", "ig_jimmyboston"),
    ("JIMMYDISANTO", "ig_jimmydisanto"),
    ("JOEMINUTEMAN", "ig_joeminuteman"),
    ("JOHNNYKLEBITZ", "ig_johnnyklebitz"),
    ("JOSEF 约瑟夫", "ig_josef"),
    ("JOSH 杰克", "ig_josh"),
    ("KERRYMCINTOSH", "ig_kerrymcintosh"),
    ("LAMARDAVIS", "ig_lamardavis"),
    ("LAZLOW", "ig_lazlow"),
    ("LESTERCREST", "ig_lestercrest"),
    ("LIFEINVAD", "ig_lifeinvad_01"),
    ("LIFEINVAD", "ig_lifeinvad_02"),
    ("MAGENTA", "ig_magenta"),
    ("MANUEL 曼努埃尔", "ig_manuel"),
    ("MARNIE 玛妮", "ig_marnie"),
    ("MARYANN 玛丽安", "ig_maryann"),
    ("MAUDE 莫德", "ig_maude"),
    ("MICHELLE 米歇尔", "ig_michelle"),
    ("MILTON 密尔顿", "ig_milton"),
    ("MOLLY 莫莉", "ig_molly"),
    ("MRK MRK", "ig_mrk"),
    ("MRSPHILLIPS", "ig_mrsphillips"),
    ("MRS_THORNHILL", "ig_mrs_thornhill"),
    ("NATALIA 娜塔莉亚", "ig_natalia"),
    ("NERVOUSRON", "ig_nervousron"),
    ("NIGEL 奈吉尔", "ig_nigel"),
    ("OLD_MAN1A", "ig_old_man1a"),
    ("OLD_MAN2", "ig_old_man2"),
    ("OMEGA 欧米茄", "ig_omega"),
    ("ONEIL 奥尼尔", "ig_oneil"),
    ("ORLEANS 奥尔良", "ig_orleans"),
    ("ORTEGA 奥尔特加", "ig_ortega"),
    ("PAPER", "ig_paper"),
    ("PATRICIA 帕特丽夏", "ig_patricia"),
    ("PRIEST 牧师", "ig_priest"),
    ("PROLSEC", "ig_prolsec_02"),
    ("GANG 岗", "ig_ramp_gang"),
    ("HIC HIC", "ig_ramp_hic"),
    ("HIPSTER 赶时髦的人", "ig_ramp_hipster"),
    ("MEX 墨西哥", "ig_ramp_mex"),
    ("ROCCOPELOSI", "ig_roccopelosi"),
    ("RUSSIANDRUNK", "ig_russiandrunk"),
    ("SCREEN_WRITER", "ig_screen_writer"),
    ("SIEMONYETARIAN", "ig_siemonyetarian"),
    ("SOLOMON 所罗门", "ig_solomon"),
    ("STEVEHAINS", "ig_stevehains"),
    ("STRETCH 拉伸", "ig_stretch"),
    ("TALINA 塔利纳", "ig_talina"),
    ("TANISHA Tanisha", "ig_tanisha"),
    ("TAOCHENG 桃城", "ig_taocheng"),
    ("TAOSTRANSLATOR", "ig_taostranslator"),
    ("TAOSTRANSLATOR_P", "ig_taostranslator_p"),
    ("TENNISCOACH", "ig_tenniscoach"),
    ("TERRY 特里", "ig_terry"),
    ("TOMEPSILON", "ig_tomepsilon"),
    ("TONYA 童雅", "ig_tonya"),
    ("TRACYDISANTO", "ig_tracydisanto"),
    ("TRAFFICWARDEN 交通管理员", "ig_trafficwarden"),
    ("TYLERDIX", "ig_tylerdix"),
    ("WADE 韦德", "ig_wade"),
    ("ZIMBOR", "ig_zimbor"),
    ("DEADHOOKER", "mp_f_deadhooker"),
    ("FREEMODE", "mp_f_freemode_01"),
    ("MISTY", "mp_f_misty_01"),
    ("STRIPPERLITE", "mp_f_stripperlite"),
    ("PROS", "mp_g_m_pros_01"),
    ("MP_HEADTARGETS", "mp_headtargets"),
    ("CLAUDE 克劳德", "mp_m_claude_01"),
    ("EXARMY", "mp_m_exarmy_01"),
    ("FAMDD", "mp_m_famdd_01"),
    ("FIBSEC", "mp_m_fibsec_01"),
    ("FREEMODE", "mp_m_freemode_01"),
    ("MARSTON 马斯顿", "mp_m_marston_01"),
    ("NIKO", "mp_m_niko_01"),
    ("SHOPKEEP ShopKeep", "mp_m_shopkeep_01"),
    ("ARMOURED", "mp_s_m_armoured_01"),
    ("FEMBARBER", "s_f_m_fembarber"),
    ("MAID 女仆", "s_f_m_maid_01"),
    ("SHOP_HIGH", "s_f_m_shop_high"),
    ("SWEATSHOP", "s_f_m_sweatshop_01"),
    ("AIRHOSTESS 空姐", "s_f_y_airhostess_01"),
    ("BARTENDER 酒保", "s_f_y_bartender_01"),
    ("BAYWATCH 游侠", "s_f_y_baywatch_01"),
    ("COP 警察", "s_f_y_cop_01"),
    ("FACTORY", "s_f_y_factory_01"),
    ("HOOKER", "s_f_y_hooker_01"),
    ("HOOKER", "s_f_y_hooker_02"),
    ("HOOKER", "s_f_y_hooker_03"),
    ("MIGRANT 农民工", "s_f_y_migrant_01"),
    ("MOVPREM", "s_f_y_movprem_01"),
    ("RANGER 游侠", "s_f_y_ranger_01"),
    ("SCRUBS", "s_f_y_scrubs_01"),
    ("SHERIFF 警长", "s_f_y_sheriff_01"),
    ("SHOP_LOW", "s_f_y_shop_low"),
    ("SHOP_MID", "s_f_y_shop_mid"),
    ("STRIPPERLITE", "s_f_y_stripperlite"),
    ("STRIPPER 脱衣舞女", "s_f_y_stripper_01"),
    ("STRIPPER 脱衣舞女", "s_f_y_stripper_02"),
    ("SWEATSHOP", "s_f_y_sweatshop_01"),
    ("AMMUCOUNTRY", "s_m_m_ammucountry"),
    ("ARMOURED", "s_m_m_armoured_01"),
    ("ARMOURED", "s_m_m_armoured_02"),
    ("AUTOSHOP 公司", "s_m_m_autoshop_01"),
    ("AUTOSHOP 公司", "s_m_m_autoshop_02"),
    ("BOUNCER 保镖", "s_m_m_bouncer_01"),
    ("CHEMSEC", "s_m_m_chemsec_01"),
    ("CIASEC", "s_m_m_ciasec_01"),
    ("CNTRYBAR", "s_m_m_cntrybar_01"),
    ("DOCKWORK", "s_m_m_dockwork_01"),
    ("DOCTOR 医生", "s_m_m_doctor_01"),
    ("FIBOFFICE", "s_m_m_fiboffice_01"),
    ("FIBOFFICE", "s_m_m_fiboffice_02"),
    ("GAFFER 灯光师", "s_m_m_gaffer_01"),
    ("GARDENER 园丁", "s_m_m_gardener_01"),
    ("GENTRANSPORT", "s_m_m_gentransport"),
    ("HAIRDRESS 美发", "s_m_m_hairdress_01"),
    ("HIGHSEC", "s_m_m_highsec_01"),
    ("HIGHSEC", "s_m_m_highsec_02"),
    ("JANITOR 看门人", "s_m_m_janitor"),
    ("LATHANDY", "s_m_m_lathandy_01"),
    ("LIFEINVAD", "s_m_m_lifeinvad_01"),
    ("LINECOOK", "s_m_m_linecook"),
    ("LSMETRO", "s_m_m_lsmetro_01"),
    ("MARIACHI 流浪", "s_m_m_mariachi_01"),
    ("MARINE", "s_m_m_marine_01"),
    ("MARINE", "s_m_m_marine_02"),
    ("MIGRANT 农民工", "s_m_m_migrant_01"),
    ("ZOMBIE 僵尸", "u_m_y_zombie_01"),
    ("MOVPREM", "s_m_m_movprem_01"),
    ("MOVSPACE", "s_m_m_movspace_01"),
    ("PARAMEDIC 护理人员", "s_m_m_paramedic_01"),
    ("PILOT", "s_m_m_pilot_01"),
    ("PILOT", "s_m_m_pilot_02"),
    ("POSTAL 邮政", "s_m_m_postal_01"),
    ("POSTAL 邮政", "s_m_m_postal_02"),
    ("PRISGUARD", "s_m_m_prisguard_01"),
    ("SCIENTIST 科学家", "s_m_m_scientist_01"),
    ("SECURITY 安全", "s_m_m_security_01"),
    ("SNOWCOP", "s_m_m_snowcop_01"),
    ("STRPERF", "s_m_m_strperf_01"),
    ("STRPREACH", "s_m_m_strpreach_01"),
    ("STRVEND", "s_m_m_strvend_01"),
    ("TRUCKER 卡车司机", "s_m_m_trucker_01"),
    ("UPS", "s_m_m_ups_01"),
    ("UPS", "s_m_m_ups_02"),
    ("BUSKER 街头艺人", "s_m_o_busker_01"),
    ("AIRWORKER", "s_m_y_airworker"),
    ("AMMUCITY", "s_m_y_ammucity_01"),
    ("ARMYMECH", "s_m_y_armymech_01"),
    ("AUTOPSY", "s_m_y_autopsy_01"),
    ("BARMAN 酒保", "s_m_y_barman_01"),
    ("BAYWATCH 游侠", "s_m_y_baywatch_01"),
    ("BLACKOPS 黑色行动", "s_m_y_blackops_01"),
    ("BLACKOPS 黑色行动", "s_m_y_blackops_02"),
    ("BUSBOY 餐厅勤杂工", "s_m_y_busboy_01"),
    ("CHEF 厨师", "s_m_y_chef_01"),
    ("CLOWN 小丑", "s_m_y_clown_01"),
    ("CONSTRUCT", "s_m_y_construct_01"),
    ("CONSTRUCT", "s_m_y_construct_02"),
    ("COP 警察", "s_m_y_cop_01"),
    ("DEALER 经销商", "s_m_y_dealer_01"),
    ("DEVINSEC", "s_m_y_devinsec_01"),
    ("DOCKWORK", "s_m_y_dockwork_01"),
    ("DOORMAN 门卫", "s_m_y_doorman_01"),
    ("DWSERVICE", "s_m_y_dwservice_01"),
    ("DWSERVICE", "s_m_y_dwservice_02"),
    ("FACTORY", "s_m_y_factory_01"),
    ("FIREMAN", "s_m_y_fireman_01"),
    ("GARBAGE 垃圾", "s_m_y_garbage"),
    ("GRIP 秃鹫", "s_m_y_grip_01"),
    ("HWAYCOP", "s_m_y_hwaycop_01"),
    ("MARINE", "s_m_y_marine_01"),
    ("MARINE", "s_m_y_marine_02"),
    ("MARINE", "s_m_y_marine_03"),
    ("MIME MIME", "s_m_y_mime"),
    ("PESTCONT", "s_m_y_pestcont_01"),
    ("PILOT 飞行员", "s_m_y_pilot_01"),
    ("PRISMUSCL", "s_m_y_prismuscl_01"),
    ("PRISONER 囚犯", "s_m_y_prisoner_01"),
    ("RANGER 游侠", "s_m_y_ranger_01"),
    ("ROBBER", "s_m_y_robber_01"),
    ("SHERIFF 警长", "s_m_y_sheriff_01"),
    ("SHOP_MASK", "s_m_y_shop_mask"),
    ("STRVEND", "s_m_y_strvend_01"),
    ("SWAT SWAT模型", "s_m_y_swat_01"),
    ("USCG 美国海岸警卫队", "s_m_y_uscg_01"),
    ("VALET 服务员", "s_m_y_valet_01"),
    ("WAITER 沃尔特", "s_m_y_waiter_01"),
    ("WINCLEAN", "s_m_y_winclean_01"),
    ("XMECH", "s_m_y_xmech_01"),
    ("XMECH", "s_m_y_xmech_02"),
    ("CORPSE 尸体", "u_f_m_corpse_01"),
    ("MIRANDA 米兰达", "u_f_m_miranda"),
    ("PROMOURN", "u_f_m_promourn_01"),
    ("MOVIESTAR 电影明星", "u_f_o_moviestar"),
    ("PROLHOST", "u_f_o_prolhost_01"),
    ("BIKERCHIC", "u_f_y_bikerchic"),
    ("COMJANE", "u_f_y_comjane"),
    ("CORPSE 尸体", "u_f_y_corpse_01"),
    ("CORPSE 尸体", "u_f_y_corpse_02"),
    ("HOTPOSH", "u_f_y_hotposh_01"),
    ("JEWELASS", "u_f_y_jewelass_01"),
    ("MISTRESS", "u_f_y_mistress"),
    ("POPPYMICH", "u_f_y_poppymich"),
    ("PRINCESS 公主", "u_f_y_princess"),
    ("SPYACTRESS", "u_f_y_spyactress"),
    ("ALDINAPOLI", "u_m_m_aldinapoli"),
    ("BANKMAN", "u_m_m_bankman"),
    ("BIKEHIRE", "u_m_m_bikehire_01"),
    ("FIBARCHITECT", "u_m_m_fibarchitect"),
    ("FILMDIRECTOR", "u_m_m_filmdirector"),
    ("GLENSTANK", "u_m_m_glenstank_01"),
    ("GRIFF", "u_m_m_griff_01"),
    ("JESUS 耶稣", "u_m_m_jesus_01"),
    ("JEWELSEC", "u_m_m_jewelsec_01"),
    ("JEWELTHIEF", "u_m_m_jewelthief"),
    ("MARKFOST", "u_m_m_markfost"),
    ("PARTYTARGET", "u_m_m_partytarget"),
    ("PROLSEC", "u_m_m_prolsec_01"),
    ("PROMOURN", "u_m_m_promourn_01"),
    ("RIVALPAP", "u_m_m_rivalpap"),
    ("SPYACTOR", "u_m_m_spyactor"),
    ("WILLYFIST", "u_m_m_willyfist"),
    ("FINGURU", "u_m_o_finguru_01"),
    ("TAPHILLBILLY", "u_m_o_taphillbilly"),
    ("TRAMP", "u_m_o_tramp_01"),
    ("ABNER", "u_m_y_abner"),
    ("ANTONB", "u_m_y_antonb"),
    ("BABYD", "u_m_y_babyd"),
    ("BAYGOR", "u_m_y_baygor"),
    ("BURGERDRUG", "u_m_y_burgerdrug_01"),
    ("CHIP", "u_m_y_chip"),
    ("CYCLIST", "u_m_y_cyclist_01"),
    ("FIBMUGGER", "u_m_y_fibmugger_01"),
    ("GUIDO", "u_m_y_guido_01"),
    ("GUNVEND", "u_m_y_gunvend_01"),
    ("HIPPIE", "u_m_y_hippie_01"),
    ("IMPORAGE", "u_m_y_imporage"),
    ("JUSTIN 贾斯汀", "u_m_y_justin"),
    ("MANI", "u_m_y_mani"),
    ("MILITARYBUM", "u_m_y_militarybum"),
    ("PAPARAZZI 狗仔队", "u_m_y_paparazzi"),
    ("PARTY", "u_m_y_party_01"),
    ("POGO", "u_m_y_pogo_01"),
    ("PRISONER 囚犯", "u_m_y_prisoner_01"),
    ("BENNY", "ig_benny"),
    ("G", "ig_g"),
    ("VAGSPEAK", "ig_vagspeak"),
    ("VAGFUN", "mp_m_g_vagfun_01"),
    ("BOATSTAFF", "mp_m_boatstaff_01"),
    ("FEMBOATSTAFF", "mp_f_boatstaff_01"),
)