coords = (
    ('任务相关', 'tasks'),
    ('房屋销售标志', 'ForSaleSign'),
    ('太空船碎片', 'SpaceshipPart'),
    ('信件碎片', 'LetterScrap'),
    ('核废料', 'NuclearWaste'),
    ('潜艇碎片', 'SubmarinePiece'),
    ('猴子镶嵌画', 'MonkeyMosaic'),
    ('隐藏包裹', 'HiddenPackage'),
    ('迷幻仙人掌', 'Peyote'),
    ('特技跳跃', 'StuntJump'),
    ('桥下', 'UnderTheBridge'),
    ('Epsilon邪教册子', 'EpsilonTract'),
    ('Epsilon邪教任务车辆', 'EpsilonVehicles'),
)