modules = [
    ("角色修改", "character"),
    # ("道具修改", "item"),
    # ("职业修改", "proficiency"),
    # ("程序杂项修改", "sundry"),
    # ("地图静态形象修改", "proficiencyMapImage"),
    # ("地图动态形象修改", "proficiencyMapImage"),
    # ("地图修改", "map"),
    # ("斗技场修改", "other"),
    # ("人物配色-职业部分", "color"),
    # ("人物配色-颜色部分", "color"),
    # ("特技修改", "tunt"),
    # ("武器动画修改", "other"),
    # ("章节数据修改", "chapterData"),
    # ("章节配置修改", "chapterConfiguration"),
    # ("支援属性加成修改", "other"),
    # ("转职修改", "other"),
    # ("Boss战BGM", "other"),
]